name: Check Status ACB

on:
  schedule:
    - cron: '0 * * * *' # Ejecutar cada hora en punto
  workflow_dispatch: # Permite ejecutar manual

permissions:
  contents: write

jobs:
  check-and-process:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run script
      env:
        # Si tu funcion enviar_newsletter necesita contraseñas, ponlas aquí
        EMAIL_USER: ${{ secrets.EMAIL_USER }} 
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      run: python check_status.py

    - name: Commit & Push changes
      run: |
        git config --global user.name 'ACB Bot'
        git config --global user.email 'bot@noreply.github.com'
        # Añadimos LOG y el archivo de BUFFER (importante para la cuenta atrás)
        git add data/log.txt data/buffer_control.txt
        # Commit solo si hay cambios, si no, no falla
        git commit -m "Auto: Update status J${{ github.run_number }}" || exit 0
        git push
